<a href="https://colab.research.google.com/github/lithikaneelakandan56-ctrl/ml_practice/blob/main/ML/day02_data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Day 2: Data Preprocessing

## Topics
#- Data Preprocessing
#- Missing Values
#- Categorical Data
#- One-Hot Encoding
#- Features and Target
#- Train-Test Split
#- Feature Scaling

In [ ]:
## 1. What is Data Preprocessing?

#Data preprocessing is the process of cleaning and transforming raw data into a format suitable for machine learning models.
#Common preprocessing steps include:
#- Handling missing values
#- Encoding categorical data
#- Feature scaling
#- Splitting data into training and testing sets

In [2]:
import pandas as pd
import numpy as np

In [3]:
# Creating a sample data set
data = {
    "Age": [21, 25, 30, 35, np.nan, 40],
    "Salary": [25000, 35000, 50000, 65000, 70000, 80000],
    "City": ["Chennai", "Bangalore", "Chennai", "Mumbai", "Bangalore", "Chennai"],
    "Purchased": ["Yes", "No", "Yes", "No", "Yes", "Yes"]
}
df = pd.DataFrame(data)
df

    Age  Salary       City Purchased
0  21.0   25000    Chennai       Yes
1  25.0   35000  Bangalore        No
2  30.0   50000    Chennai       Yes
3  35.0   65000     Mumbai        No
4   NaN   70000  Bangalore       Yes
5  40.0   80000    Chennai       Yes

In [9]:
## 3. Understanding the Dataset
df.isnull().sum()# it tells the null in any data
df.info()# it gives information about the dataset
df.head()#gives first 4 rows and columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Age        5 non-null      float64
 1   Salary     6 non-null      int64
 2   City       6 non-null      object
 3   Purchased  6 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 324.0+ bytes

    Age  Salary       City Purchased
0  21.0   25000    Chennai       Yes
1  25.0   35000  Bangalore        No
2  30.0   50000    Chennai       Yes
3  35.0   65000     Mumbai        No
4   NaN   70000  Bangalore       Yes

In [15]:
## 4. Handling Missing Values
#Missing values can cause problems when training machine learning models.Here, the Age column contains a missing value. We will replace the missing value with the median of the Age column.
df["Age"]=df["Age"].fillna(df["Age"].median())
df

    Age  Salary       City Purchased
0  21.0   25000    Chennai       Yes
1  25.0   35000  Bangalore        No
2  30.0   50000    Chennai       Yes
3  35.0   65000     Mumbai        No
4  30.0   70000  Bangalore       Yes
5  40.0   80000    Chennai       Yes

In [16]:
df.isnull().sum()#checking if there is still any null values

Age          0
Salary       0
City         0
Purchased    0
dtype: int64

In [17]:
## 5. Categorical Data

#Categorical data contains values such as names or categories.
"""
Example:
- Chennai
- Bangalore
- Mumbai
Machine learning models generally require numerical input.
Therefore, we convert categorical data into numerical columns.
"""
df=pd.get_dummies(df,columns=["City"])
df

    Age  Salary Purchased  City_Bangalore  City_Chennai  City_Mumbai
0  21.0   25000       Yes           False          True        False
1  25.0   35000        No            True         False        False
2  30.0   50000       Yes           False          True        False
3  35.0   65000        No           False         False         True
4  30.0   70000       Yes            True         False        False
5  40.0   80000       Yes           False          True        False

In [18]:
''' 6. Converting the Target into Numbers

The Purchased column contains:

Yes → 1
No → 0

This converts the target into numerical values.'''
df["Purchased"] = df["Purchased"].map({
    "Yes": 1,
    "No": 0
})
df

    Age  Salary  Purchased  City_Bangalore  City_Chennai  City_Mumbai
0  21.0   25000          1           False          True        False
1  25.0   35000          0            True         False        False
2  30.0   50000          1           False          True        False
3  35.0   65000          0           False         False         True
4  30.0   70000          1            True         False        False
5  40.0   80000          1           False          True        False

In [19]:
''' 7. Separating Features and Target

X represents the input features.

y represents the target/output that we want the model to predict.'''
X = df.drop("Purchased", axis=1)
y = df["Purchased"]
print("Features (X):")
print(X)
print("\nTarget (y):")
print(y)

Features (X):
    Age  Salary  City_Bangalore  City_Chennai  City_Mumbai
0  21.0   25000           False          True        False
1  25.0   35000            True         False        False
2  30.0   50000           False          True        False
3  35.0   65000           False         False         True
4  30.0   70000            True         False        False
5  40.0   80000           False          True        False

Target (y):
0    1
1    0
2    1
3    0
4    1
5    1
Name: Purchased, dtype: int64

In [23]:
''' 8. Train-Test Split

We divide the dataset into:

- Training data: used to train the model
- Testing data: used to evaluate the model

Here, 80% of the data is used for training and 20% for testing.'''
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
print("Training Data of X",X_train)
print("Testing Data of X",X_test)
print("Training Data of y",y_train)
print("Testting Data of y",y_test)

Training Data of X     Age  Salary  City_Bangalore  City_Chennai  City_Mumbai
5  40.0   80000           False          True        False
2  30.0   50000           False          True        False
4  30.0   70000            True         False        False
3  35.0   65000           False         False         True
Testing Data of X     Age  Salary  City_Bangalore  City_Chennai  City_Mumbai
0  21.0   25000           False          True        False
1  25.0   35000            True         False        False
Training Data of y 5    1
2    1
4    1
3    0
Name: Purchased, dtype: int64
Testting Data of y 0    1
1    0
Name: Purchased, dtype: int64

In [25]:
# mini challenge
df["Experience"]=[1,2,5,7,12,10]
df["Salary_per_Experience"]=df["Salary"]/df["Experience"]
df

,Age,Salary,Purchased,City_Bangalore,City_Chennai,City_Mumbai,Experience,Salary_per_Experience
0,21.0,25000,1,False,True,False,1,25000.000000
1,25.0,35000,0,True,False,False,2,17500.000000
2,30.0,50000,1,False,True,False,5,10000.000000
3,35.0,65000,0,False,False,True,7,9285.714286
4,30.0,70000,1,True,False,False,12,5833.333333
5,40.0,80000,1,False,True,False,10,8000.000000

In [ ]:
''' 9. Feature Scaling

Feature scaling is used to bring numerical features into a similar range.

For example:

Age → 18 to 60
Salary → 20,000 to 2,00,000

Because these features have very different scales, scaling can be useful
for many machine learning algorithms.

Common methods:
- Standardization
- Min-Max Scaling
2. Standardization
Standardization transforms data so that approximately:
Mean = 0
Standard deviation = 1
Formula:
z=x−μ/σ
3. Min-Max Scaling
Another common method is Min-Max Scaling.
It generally converts values into the range:
0 to 1
Formula:
x′=x−xmin/xmax−xmin
'''

In [29]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)
X_scaled

array([[-1.47787534, -1.49923528, -0.70710678,  1.        , -0.4472136 ],
       [-0.83298428, -0.98521175,  1.41421356, -1.        , -0.4472136 ],
       [-0.02687046, -0.21417647, -0.70710678,  1.        , -0.4472136 ],
       [ 0.77924336,  0.55685882, -0.70710678, -1.        ,  2.23606798],
       [-0.02687046,  0.81387058,  1.41421356, -1.        , -0.4472136 ],
       [ 1.58535718,  1.3278941 , -0.70710678,  1.        , -0.4472136 ]])

In [27]:
X_scaled=pd.DataFrame(X_scaled,columns=X.columns)
X_scaled

        Age    Salary  City_Bangalore  City_Chennai  City_Mumbai
0 -1.477875 -1.499235       -0.707107           1.0    -0.447214
1 -0.832984 -0.985212        1.414214          -1.0    -0.447214
2 -0.026870 -0.214176       -0.707107           1.0    -0.447214
3  0.779243  0.556859       -0.707107          -1.0     2.236068
4 -0.026870  0.813871        1.414214          -1.0    -0.447214
5  1.585357  1.327894       -0.707107           1.0    -0.447214

In [ ]:
'''fit() → learns the mean and standard deviation from the data.
transform() → uses those values to scale the data.
fit_transform() → does both together.'''

In [31]:
#min max scaling
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_minmax = scaler.fit_transform(X)
X_minmax = pd.DataFrame(X_minmax,columns=X.columns)
X_minmax

        Age    Salary  City_Bangalore  City_Chennai  City_Mumbai
0  0.000000  0.000000             0.0           1.0          0.0
1  0.210526  0.181818             1.0           0.0          0.0
2  0.473684  0.454545             0.0           1.0          0.0
3  0.736842  0.727273             0.0           0.0          1.0
4  0.473684  0.818182             1.0           0.0          0.0
5  1.000000  1.000000             0.0           1.0          0.0